config/routes.rb
Rails.application.routes.draw do
  post "hello", to: "game_state_events#hello" # for testing (a button with post messod is shown in game_state_events#home view)

  resources :steam_accounts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  post "game_event", to: "game_state_events#game_event"
  root "steam_accounts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/killtracker_unit.rb
class KilltrackerUnit < ApplicationRecord
  belongs_to :person
  belongs_to :tracked_steam_account, class_name: "SteamAccount", foreign_key: "steam_account_id"
end

app/models/match_stat_record.rb
class MatchStatRecord < ApplicationRecord
  belongs_to :steam_account, optional: false
  before_save :set_type, :set_previous_kills

  private

  def set_previous_kills
    return if previous_kills
    # Find the most recent match_stat_record of type 'event' for the same user
    last_event_record = steam_account.match_stat_records
                                   .where(request_type: 'event')
                                   .order(timestamp: :desc)
                                   .first

    # If such a record exists, set previous_kills to the kills of that record
    self.previous_kills = last_event_record ? last_event_record.kills : nil
  end

  def set_type
    # Find the most recent record for the same steam_account
    last_record = steam_account.match_stat_records.order(timestamp: :desc).first

    # Check if the last record exists and if all fields match
    if last_record &&
       last_record.kills == kills &&
       last_record.assists == assists &&
       last_record.deaths == deaths &&
       last_record.mvps == mvps &&
       last_record.score == score

      # If all values are the same, set the type to "heartbeat"
      self.request_type = "heartbeat_or_other"
    else
      self.request_type = "event"
    end
  end
end

app/models/person.rb
class Person < ApplicationRecord
  has_one :steam_account, dependent: :destroy
  has_one :killtracker_unit

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/models/steam_account.rb
class SteamAccount < ApplicationRecord
  validates :steamid, presence: true, uniqueness: true, numericality: { only_integer: true }
  validates :nickname, presence: true
  validates :kills, numericality: { only_integer: true }
  validates :person_id, uniqueness: true, allow_nil: true

  has_many :match_stat_records
  has_many :killtracker_units
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/game_state_events_controller.rb
class GameStateEventsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :game_event

  def game_event
    # implement params.require and params.permit in future
    permitted_params = permit_params()


    steamid = permitted_params&.dig :provider, :steamid
    player = SteamAccount.find_by(steamid: steamid) # can be nil if player not found
    return render_player_not_found(steamid) unless player


    new_match_data = permitted_params&.dig :player, :match_stats # can be nil if in menu

    return render json: { error: "Match data missing", steamid: player&.steamid }, status: :ok if new_match_data.nil?

    previous_match_data = permitted_params&.dig :previously, :player, :match_stats # can be missing in request therefore nil handling below-

    new_match_stat_record = create_match_stat_record(new_match_data, previous_match_data, player, permitted_params)

    return render json: { error: "Match data missing", steamid: player&.steamid }, status: :ok if new_match_stat_record.request_type == "heartbeat_or_other"


    killcount = new_match_data.dig(:kills)
    previous_killcount = previous_match_data&.dig(:kills) || new_match_stat_record.previous_kills

    new_kills = if killcount.nil? || previous_killcount.nil?
      0
    else
      killcount - previous_killcount
    end

    new_kills = new_kills.clamp(0, 1) # prevent too many or negative kills from being added

    player.kills += new_kills

    if player.save
      logger.info "SteamAccount kills updated"
      return render json: { message: "SteamAccount kills updated", kills: player.kills, status: :ok}
    end

    return render json: { message: "Failed to update kills for SteamAccount", status: :ok}
  end

  private

  def create_match_stat_record(new_match_data, previous_match_data, player, permitted_params)
    timestamp = permitted_params&.dig :provider, :timestamp

    new_match_stat_record = MatchStatRecord.new(new_match_data)
    new_match_stat_record.steam_account = player
    new_match_stat_record.timestamp = Time.at(timestamp)
    new_match_stat_record.previous_kills = previous_match_data&.dig(:kills)


    return new_match_stat_record if new_match_stat_record.save
    return false
  end

  def render_player_not_found(player)
    render json: { error: "SteamAccount not found in database", steamid: player&.steamid }, status: :ok
  end

  def permit_params
    params.permit(
      provider: [:timestamp, :steamid, :name, :version, :appid],
      player: [
        :true,
        {
          match_stats: [:kills, :assists, :deaths, :mvps, :score]
        }
      ],
      previously: {
        provider: [:timestamp, :steamid, :name, :version, :appid],
        match_stats: [:kills, :assists, :deaths, :mvps, :score],
        player: [
          :true,
          {
            match_stats: [:kills, :assists, :deaths, :mvps, :score]
          }
        ],
      },
      game_state_event: {
        provider: [:timestamp, :steamid, :name, :version, :appid],
        player: {
          match_stats: [:kills, :assists, :deaths, :mvps, :score]
        },
        previously: {
          provider: [:timestamp, :steamid, :name, :version, :appid],
          match_stats: [:kills, :assists, :deaths, :mvps, :score],
          player: [
            :true,
            {
              match_stats: [:kills, :assists, :deaths, :mvps, :score]
            }
          ],
        }
      },
    )
  end
end

app/controllers/steam_accounts_controller.rb
class SteamAccountsController < ApplicationController
  before_action :set_steam_account, only: %i[ show edit update destroy ]

  def index
    @steam_accounts = SteamAccount.all
  end

  def show
    respond_to do |format|
      format.html # Renders show.html.erb by default
      format.json { render json: @steam_account } # Renders JSON response
    end
  end

  def new
    @steam_account = SteamAccount.new
  end

  def create
    @steam_account = SteamAccount.new steam_account_params


    if @steam_account.save
      redirect_to @steam_account, notice: 'Steam Account was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @steam_account.update(steam_account_params)
      redirect_to steam_account_path(@steam_account), notice: "Steam Account successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @steam_account.destroy
    redirect_to root_url, status: :see_other
  end

  private

  def set_steam_account
    @steam_account = SteamAccount.find_by(id: params[:id]) || SteamAccount.find_by(steamid: params[:id])
  end

  def steam_account_params
    params.require(:steam_account).permit(:nickname, :steamid, :kills, :person_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_state_events_helper.rb
module GameStateEventsHelper
end

app/helpers/steam_accounts_helper.rb
module SteamAccountsHelper
end

app/helpers/steam_users_helper.rb
module SteamAccountsHelper
end

app/views/game_state_events/home.html.erb
<h1>GameStateEvents#home</h1>
<p>Find me in app/views/game_state_events/home.html.erb</p>
<%= button_to "Say Hello", hello_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cs2 Killtracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/steam_accounts/edit.html.erb
<h1>Create a New SteamAccount</h1>

<%= form_with(model: @steam_account, local: true) do |form| %>
  <% if @steam_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@steam_account.errors.count, "error") %> prohibited this steam_account from being saved:</h2>

      <ul>
        <% @steam_account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :steamid %>
    <%= form.text_field :steamid %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
  </div>

  <div class="field">
    <%= form.label :kills %>
    <%= form.number_field :kills %>
  </div>

  <div class="field">
    <%= form.label :Owner %>
    <%= form.collection_select :person_id, Person.all, :id, :full_name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit "Update SteamAccount" %>
  </div>
<% end %>

<%= link_to 'Back', steam_accounts_path %>

app/views/steam_accounts/index.html.erb
<h1>Steam Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Steam ID</th>
      <th>Kills</th>
      <th>Owner (person_id)</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @steam_accounts.each do |steam_account| %>
      <tr>
        <td><%= steam_account.nickname %></td>
        <td><%= steam_account.steamid %></td>
        <td><%= steam_account.kills %></td>
        <td><%= steam_account.person.id %></td>
        <td>
          <%= link_to 'Show', steam_account_path(steam_account) %> |
          <%= link_to 'Edit', edit_steam_account_path(steam_account) %> |
          <%= link_to 'Delete', steam_account, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Steam Account', new_steam_account_path %>

app/views/steam_accounts/new.html.erb
<h1>Create a New SteamAccount</h1>

<%= form_with(model: @steam_account, local: true) do |form| %>
<%= debug(@steam_account.errors.full_messages) %>
<%= debug(@steam_account.inspect) %>
  <% if @steam_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@steam_account.errors.count, "error") %> prohibited this steam_account from being saved:</h2>

      <ul>
        <% @steam_account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :steamid %>
    <%= form.text_field :steamid %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
  </div>

  <div class="field">
    <%= form.label :kills %>
    <%= form.number_field :kills %>
  </div>

  <div class="actions">
    <%= form.submit "Create SteamAccount" %>
  </div>
<% end %>

app/views/steam_accounts/show.html.erb
<h1><%= @steam_account.nickname %></h1>

<p>
   <strong>nickname: </strong> <%= @steam_account.nickname %><br />
   <strong>steamid :</strong> <%= @steam_account.steamid %><br />
   <strong>kills</strong> <%= @steam_account.kills %><br />
   <strong>Owner</strong> <%= @steam_account.person.full_name %><br />
</p>


<hr />

<%= link_to 'Back', steam_accounts_path %>